from .query import (
    DEFAULT_FUNCTION_QUERY_TEXT_DESCRIPTION_TMPL,
)
from .sql import (
    DEFAULT_FUNCTION_QUERY_NLSQL_DESCRIPTION_TMPL,
    DEFAULT_FUNCTION_QUERY_SQL_DESCRIPTION_TMPL,
    DEFAULT_TABLE_DESCRIPTION_TMPL,
)

__all__ = [
    "DEFAULT_TABLE_DESCRIPTION_TMPL",
    "DEFAULT_FUNCTION_QUERY_TEXT_DESCRIPTION_TMPL",
    "DEFAULT_FUNCTION_QUERY_SQL_DESCRIPTION_TMPL",
    "DEFAULT_FUNCTION_QUERY_NLSQL_DESCRIPTION_TMPL",
]
